### PR TITLE
ds-325 fix link isUnderline

### PR DESCRIPTION
**Pull request by bibifrost**

### CODE REVIEW

**Comment by JonathanLefebvreV** [comment]
@bibifrost I would like if you reproduce the problem in the ShowCase drupal, and comment in this PR the "before / After" to prove this fix work

**Comment by bibifrost** [comment]
> @bibifrost I would like if you reproduce the problem in the ShowCase drupal, and comment in this PR the "before / After" to prove this fix work

Before:
image
After:
image

**Comment by JonathanLefebvreV** [comment]
Thanks!

**Review by JonathanLefebvreV — CHANGES_REQUESTED** [review]
Only need the changelog and good to go

**Comment by bibifrost** [comment]
> Only need the changelog and good to go

Bien vu. Done

**Review by JonathanLefebvreV — APPROVED** [review]

**Pull request merged**
